# Site settings
title: f0ld.space
email: f0ldspace00@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple Jekyll blog hosted on GitHub Pages.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://f0ld.space" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
remote_theme: f0ldspace/jekyll-theme-console
style: light
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Console theme settings
header_pages:
  - index.html
  - README.md
  - tags/index.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
